import { Figtree } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

//👇 Configure our font object
const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={figtree.className}>
      <body className="text-brown">{children}</body>
    </html>
  );
}
